### ISSUE TITLE
Pugin could not load 

### ISSUE THREAD

**Issue by Oreuo** [Safrodev/fabricenchantments#40]
Every time i start the server my console gives me this error

[20:20:01 ERROR]: Could not load 'plugins\fabric-enchantments-0.7.2.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:178) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:160) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:393) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:269) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_331]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
        ... 7 more

**Comment by Safrodev** [comment]
You are trying to load a mod on a bukkit server, which only accepts plugins. Switch to a Fabric modded server if you want to use this mod.
